apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: rhtech-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rhtech-backend
  template:
    metadata:
      labels:
        app: rhtech-backend
        version: v1 
    spec:
      containers:
      - name: backend
        image: rhtech_backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /health  
            port: 3000
          initialDelaySeconds: 15
          failureThreshold: 5
        env:
        - name: DB_HOST
          value: "rhtech-db" # Nome do seu Service K8s
        - name: DB_USER
          value: "admin"     # Mudei para 'admin' para bater com o docker-compose
        - name: DB_PASSWORD
          value: "secretpassword" # Mudei para 'secretpassword'
        - name: DB_NAME
          value: "rhtech_db" # Mudei para 'rhtech_db'

