apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: rhtech-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rhtech-backend
  template:
    metadata:
      labels:
        app: rhtech-backend
        version: v1 
    spec:
      containers:
      - name: backend
        image: matias1210/rhtech-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /health  
            port: 3001
          initialDelaySeconds: 15
          failureThreshold: 5
        env:
        - name: DB_HOST
          value: "192.168.100.14" 
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "rhtech"
        - name: DB_NAME
          value: "rhtech_db"

