version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rhtech_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: rhtech_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: rhtech_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:secretpassword@db:5432/rhtech_db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: rhtech_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
