apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: rhtech-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhtech-frontend
  template:
    metadata:
      labels:
        app: rhtech-frontend
    spec:
      containers:
      - name: frontend
        image: matias1210/rhtech-frontend:fix-login 
        ports:
        - containerPort: 80 