apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: rhtech-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhtech-frontend
  template:
    metadata:
      labels:
        app: rhtech-frontend
    spec:
      containers:
      - name: frontend
<<<<<<< HEAD
        image: matias1210/rhtech-frontend:658311eddf75b99aa32e0e6fe7fc39be550c7d09
        ports:
        - containerPort: 80 
=======
        image: matias1210/rhtech-frontend:658311eddf75b99aa32e0e6fe7fc39be550c7d09
        imagePullPolicy: Always                    
        ports:
        - containerPort: 80
>>>>>>> 5f268d957228915739a7d267dae2a5753380ea11
