apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhtech-db
  labels:
    app: rhtech-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhtech-db
  template:
    metadata:
      labels:
        app: rhtech-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "rhtech"
        - name: POSTGRES_DB
          value: "rhtechdb"
