apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh
  namespace: istio-system
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      istio: mesh
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
  - port: http-envoy-prom
    interval: 15s