apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Backend
  - backend/deployment.yaml
  - backend/service.yaml
  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
  # Banco de Dados
  - db-deployment.yaml
  - db-service.yaml
  # Istio Service Mesh
  - istio/istio-gateway.yaml
  - istio/destination-rule.yaml
  - istio/virtual-service.yaml
  - istio/istio-servicemonitor.yaml
