apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: matias1210/rhtech-backend
  newName: matias1210/rhtech-backend
  newTag: 0b37cdcf4504555c35731f5b6d821e5b3a260d68
- name: matias1210/rhtech-frontend
  newName: matias1210/rhtech-frontend
  newTag: 0b37cdcf4504555c35731f5b6d821e5b3a260d68

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: backend-deployment
