apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: matias1210/rhtech-backend
  newName: matias1210/rhtech-backend
  newTag: b0427fba790bd701de82772dca73c7667002c0fe
- name: matias1210/rhtech-frontend
  newName: matias1210/rhtech-frontend
  newTag: fix-login

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: backend-deployment
