apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: matias1210/rhtech-backend
  newTag: 01aad561ce2eeaf79b7b7df53adf37e6db2dfa14

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: backend-deployment
