jobs:
  build-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src: ['backend/**']
      - if: steps.filter.outputs.src == 'true'
        name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            matias1210/rhtech-backend:${{ github.sha }}
            matias1210/rhtech-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src: ['frontend/**']
      - if: steps.filter.outputs.src == 'true'
        name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            matias1210/rhtech-frontend:${{ github.sha }}
            matias1210/rhtech-frontend:latest
